apiVersion: batch/v1
kind: Job
metadata:
  name: ray-training
  namespace: training
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - command:
        - python
        - /app/train.py
        image: gcr.io/dra-dml/ray-training:v1
        imagePullPolicy: Always
        name: ray-worker
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
        volumeMounts:
        - mountPath: /app/model_output
          name: model-storage
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: model-storage
