apiVersion: batch/v1
kind: Job
metadata:
  name: {{job_name}}
  namespace: training
spec:
  completions: 1
  template:
    spec:
      containers:
      - name: horovod-worker
        image: gcr.io/dra-dml/horovod-training:v1
        command: ["horovodrun", "-np", "{{num_workers}}", "-H", "localhost:{{num_workers}}", "python", "/app/train.py"]
        resources:
          limits:
            cpu: "{{cpu_limit}}"
            memory: "{{memory_limit}}"
        volumeMounts:
        - name: model-storage
          mountPath: /app/model_output
      restartPolicy: Never
      volumes:
      - name: model-storage
        emptyDir: {}

