apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      release: monitoring
  endpoints:
    - port: web
      interval: 30s
